### ISSUE TITLE
Notebook format general improvements

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#110]
It would be good to find a way to have the notebooks filled out for online viewing, but for learning in workshop have them use versions with none of the pre-filled output, forcing them to run the cells. It would also be good to give them versions with less of the code so we can live-code more things.

This might be do-able with some custom cell metadata and some custom export steps. Another option would be an extension that we have set up in the environment.

**Comment by jrleeman** [comment]
The filled and unfilled notebooks came up again in #143

**Comment by jrleeman** [comment]
Millersville notes

* [ ] Have reference, filled notebook
* [ ] Have separate exercise notebook, blank with only imports, markdown description cells, and comments in answer cells
* [ ] Teach from blank notebook

**Comment by dopplershift** [comment]
Let's just leave it to percolate until after this spring's round.

**Comment by jrleeman** [comment]
Per SciPy, I think we can agree that we should be formatting some of the cells with CSS styles (alert, success, etc) and using the load magic to load solutions into exercise notebooks.

**Comment by jrleeman** [comment]
Left open until we get the materials updated to:
* Use CSS for exercises, tips, etc.
* Use load magics for solutions

**Comment by jrleeman** [comment]
Notebooks have been improved with CSS and load magics. This worked very well at TTU and we'll be sticking with it for the workshop format.
