### ISSUE TITLE
More cohesive lesson plan

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#111]
Right now, especially on day 3 with the Siphon and MetPy lessons, all of these lessons are very independent. It would be better to break into some smaller chunks, say introduce Siphon, and then work through practical examples in one larger unit. This would eliminate some duplication of materials introducing things like NCSS.

We also don't currently have any examples combining multiple data sets, which is such a glaring omission.

**Comment by jrleeman** [comment]
Shall we close this per reviewing the new lesson plans in Google Docs?

**Comment by dopplershift** [comment]
Done.
