### ISSUE TITLE
Update: Satellite Images

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#124]
Update the satellite imagery tutorial to follow our new class outline.

**Comment by jrleeman** [comment]
We should discuss the merits of switching to GOES-16 and/or trying to show GINI as well. I think putting all of the eggs in the GOES-16 basket hits the newest flashiest thing, but misses some of the more standard practices we need to teach.

**Comment by dopplershift** [comment]
I understand the spirit of what you're saying, but let's not oversell GINI here. GINI is a NOAAPORT-specific format that seems a bit fringe, and frankly only exists in MetPy because I was debugging it on the netCDF-java side.

I'm not saying abandon it, but let's not treat GINI as a core file format for meteorology. At any rate, both satellite data sources should be drop-in replacements for each other, and if that's not the case, we should be considering getting in any necessary tweaks to GINI for MetPy 0.5.
