### ISSUE TITLE
Workshop materials

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#13]
- [x] git/github #16 
- [x] conda/binstar #17 
- [x] Ipython notebook #22 
- [x] numpy/matplotlib #18 
- [x] Geoscience vis w/ matplotlib/cartopy #19 
- [x] NetCDF case study #21 
- [x] Pythonic #23 
- [x] Siphon #24 
- [x] MetPy #25 
- [x] Point obs #20 
- [x] WMS #26 
- [x] Radar composites #27

**Comment by dopplershift** [comment]
This is about review of content, or making sure new ones exist.

**Comment by dopplershift** [comment]
Would also be good to make sure they all make the best use of `siphon` and `metpy` possible.

**Comment by dopplershift** [comment]
While WMS notebook is Python 3 compatible, and I removed use of pyproj from Basemap, it still uses Basemap to plot.

Cartopy has support for WMS, so we should really use that and finally remove all uses of basemap.

**Comment by lesserwhirls** [comment]
Been on my list for...ummm...let's just say months and cl it good. I'll try
to get it going tonight.

In lameness,

Sean

**Comment by lesserwhirls** [comment]
Ok, WMS notebook no longer uses Basemap in favor of CartoPy. See PR #15

**Comment by dopplershift** [comment]
Looks like they're all done.
