### ISSUE TITLE
Improve git lesson materials

### ISSUE THREAD

**Issue by jrleeman** [Unidata/unidata-python-workshop#150]
Based of feedback in Millersville #143 - we need to do some improvement on the git materials. Even if we don't teach it as part of the 2-day workshop, these are good things to improve.

**Consider whacking this whole lesson**

* [x] Maybe explain workflow with graphics first?
* [ ] Magazine rack analogy
* [x] Explain what a repo is before we create one - and what should be a repo
* [ ] Add promise of making graphics before the end of the day to encourage getting through the hard start with git (start with setting up Python?)
* [ ] Add git pretty log command
* [x] Maybe use plain text initially since they don't know python yet?
* [ ] If we still use python, bug calc.py initially so you can debug it later and commit the fix

**Comment by jrleeman** [comment]
Any thoughts @dopplershift on if we should start with git and promise cool things by the end of the day or if we should start with python and return to git?

**Comment by dopplershift** [comment]
Unless we go away from having the notebooks committed to the repository, starting with git seems to be the most natural, since we use `git clone` to get the environment file.

**Comment by jrleeman** [comment]
They could do it w/o knowing what's going on at the time.

**Comment by dopplershift** [comment]
Sure they *could*, but I'm not seeing the benefit. I like to avoid saying "we'll cover this later" as much as possible.

**Comment by dopplershift** [comment]
As far as plain text, remember: we *assume* Python knowledge. We are *NOT* teaching basic Python in this workshop, so I have no problem with using basic Python code.

**Comment by jrleeman** [comment]
This was addressed in #180
