### ISSUE TITLE
Improve Primer Materials

### ISSUE THREAD

**Issue by jrleeman** [Unidata/unidata-python-workshop#153]
* [ ] Question folks as to what the output should be before running it
* [ ] Maybe do this all in interactive shell?
* [ ] Point out that MATLAB is 1-based (and maybe why zero based is a thing?)
* [x] Add units to speed example
* [x] Pressure typo in exercises
* [x] Use MetPy constants
* [ ] Talk about default values in function docstrings
* [x] Kelvin issue in example
* [x] Add tests for examples
* [x] Add np.ndim example
* [x] Need a break before getting deep into time series stuff
* [x] Add boolean arrays back
* [x] Ran long
* [ ] Maybe use some graphics to help them conceptualize multi-dimensional arrays?
* [x] Clear the notebook before running
* [ ] Have a few as comments, ask for what they think the answer will be (ether pad histogram?)
* [ ] Show tab completion of units and completeness (yes, furlongs/fortnight works and is a bit a humor)

**Comment by dopplershift** [comment]
First cut done in #183.
