### ISSUE TITLE
Post our filled out examples post workshop

### ISSUE THREAD

**Issue by jrleeman** [Unidata/unidata-python-workshop#156]
We had a request to share our filled out example notebooks after Millersville. Not sure what the best way to do this is without really bloating the repo.

**Comment by jrleeman** [comment]
Any thoughts on this @dopplershift? Maybe it's not worth doing as I have a hard time seeing how to do it for every single workshop.

**Comment by dopplershift** [comment]
I would rather have a static "key" for the exercises in the repo.

**Comment by jrleeman** [comment]
Based on the current exercise format - do we even need that? It could be said that the lesson notebook is the key

**Comment by dopplershift** [comment]
I'd expect things broken up a bit more in the lesson, plus maybe the exercise is a variation on the original material.

**Comment by jrleeman** [comment]
Fair - I can go for a solutions notebook.

**Comment by jrleeman** [comment]
I'm thinking we can use the notebooks we fill at OU as the solutions - so I'll move this to the Madison milestone. We can add those during the OU workshop.

**Comment by jrleeman** [comment]
This will close with #231 as we begin to implement loading solutions with `%load` magic

**Comment by jrleeman** [comment]
Going to close as we're implementing the new strategy in our newest format iteration.
