### ISSUE TITLE
Improve Satellite Lesson

### ISSUE THREAD

**Issue by jrleeman** [Unidata/unidata-python-workshop#159]
* [ ] Make a simpler RGB example that is false color or something that doesn't require the interpolation
* [x] Maybe use mesoscale sectors so that things load faster and we don't kill the server

**Comment by dopplershift** [comment]
Currently it looks like the satellite notebook is timing out our Mac builds on Travis. Can you try moving to the mesoscale sector and see if that makes things any better?
