### ISSUE TITLE
Materials for git/GitHub

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#16]
Just a tracker for reviewing/enhancing what we have for git and github.

**Comment by dopplershift** [comment]
This might be useful:
https://rogerdudler.github.io/git-guide/

**Comment by dopplershift** [comment]
I guess github can't have multiple assignees. I guess I'll just subscribe then.

**Comment by julienchastang** [comment]
Make a dummy repo??

**Comment by julienchastang** [comment]
Presentation should be done at this point
