### ISSUE TITLE
Notes from OU Workshop

### ISSUE THREAD

**Issue by jrleeman** [Unidata/unidata-python-workshop#192]
Notes from the OU workshop. Feel free to critique teaching here @laufers

# Day 1
## Git
* We **really** need to not use vim - it puts people that don't know it behind and some struggled to get back to where the lecture was.
## Notebooks
* Add questions syntax in notebooks
* Add tab completion

## Primer
* Wind direction returns degrees, so remove the unnecessary rad2deg call.
* Show `.magnitude`

**Comment by laufers** [comment]
I think the day went well.

- vi or vim There is another global variable for git that allows the learner to select the default editor for editing the commit messages. You could include that in the notes. 
- No real easy way to handle install issues, especially with Windows. Seems that each workshop that I have been has its own issues

**Comment by laufers** [comment]
This group, like the ones I have had in SWC, have a hard time understanding why it is that we do not pull in the entire library. So the question that arrises is "how do I know what part of a library I should import?" when working with a library. Not sure how one goes about explaining this when as we were talking about today, the cognitive overload that already is occurring.

**Comment by jrleeman** [comment]
Broken out into new issues.
