### ISSUE TITLE
Model Data

### ISSUE THREAD

**Issue by jrleeman** [Unidata/unidata-python-workshop#199]
It isn't data - that's a dollar. Change the name of the model data directory to model_output.

**Comment by lesserwhirls** [comment]
model ~~data~~ output

![nuke](http://orig04.deviantart.net/eaf0/f/2016/140/8/d/houdini_gif_by_cuenk89-da35hfd.gif)

**Comment by lesserwhirls** [comment]
Let me guess - @laufers?

**Comment by jrleeman** [comment]
No - he caught himself!
