### ISSUE TITLE
Materials for METAR/Point obs

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#20]
Tracker for reviewing and enhancing materials for Point observations w/ TDS

This one especially needs some love to make good use of Siphon and get rid of a lot of ugly hand-coding.

**Comment by lesserwhirls** [comment]
Just need to clean up the notebook at this point, but moved over to using siphon (much cleaner now)

**Comment by lesserwhirls** [comment]
Done (commit adc6fd193ea50e43bbaeb328107b947d4b01fa66)
