### ISSUE TITLE
Update with new Siphon API

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#218]
As of Siphon 0.5, a lot of API warts have been improved. We need to be making the best use of it here. 

I'd go ahead and update, but I'm pretty sure a lot of the verbiage and explanations need to be updated as well.

**Comment by jrleeman** [comment]
Update to siphon 0.8 and close out for Jackson state.

**Comment by dopplershift** [comment]
Fixed by #329 .
