### ISSUE TITLE
Materials for Siphon

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#24]
Need to create new materials to talk about Siphon. Steal liberally from the existing examples.

**Comment by dopplershift** [comment]
@jclark754 Notebooks look like a good start. Can you come up with some exercises to put in there? We want the students to get hands-on. It can just be derivative from what's there, but all of the other workshop notebooks explicitly call out something for them to try.

**Comment by jclark754** [comment]
You got it. Sorry thought I'd provide those during the workshop. I'll take a look at another nb and see here in a second. 

Best,

Jc

**Comment by dopplershift** [comment]
No worries, it's just nice to provide the notebook as (relatively) stand-alone parts of material, in case those from the community, who can't attend the workshop, want to try to follow in the footsteps.

**Comment by jclark754** [comment]
Doh, that makes sense. Sorry new to the workshop gig. I'll get on it right
away!

**Comment by dopplershift** [comment]
I think we're solid here.
