### ISSUE TITLE
Small matter: red-green color blindness

### ISSUE THREAD

**Issue by brianmapes** [Unidata/unidata-python-workshop#271]
One of our students mentioned that red+green is a poor choice in this example notebook. Red-blue is more inclusive. Maybe in other examples too. 

https://github.com/brianmapes/unidata-python-workshop/blob/master/notebooks/Skew_T/Upper%20Air%20and%20the%20Skew-T%20Log-P.ipynb

**Comment by jrleeman** [comment]
Hmmm - this is an interesting point. Of course these are the historical colors and the dew point is always to the left of temperature. OTOH I'm all about more inclusive and better visualizations. Blue is (sort of) commonly used for parcel path profiles. We use black for that commonly though. Just thinking out loud here.

**Comment by dopplershift** [comment]
It may be possible to tweak the shades of red/green so that they are of differing lightness and could be distinguished...I think.

**Comment by jrleeman** [comment]
OTOH I just saw some plots from Valpo that were red/blue....
