### ISSUE TITLE
vagrant

### ISSUE THREAD

**Issue by julienchastang** [Unidata/unidata-python-workshop#34]
Decide if we should keep or remove the vagrant material. Also, if interested, I have a Docker container that runs the workshop material. It is quite nice actually, nice and slim.

**Comment by dopplershift** [comment]
If we need something beyond conda, my opinion would be to use Docker.

**Comment by WardF** [comment]
I'm comfortable using Docker, assuming a use case that lends itself to that.  Julien, is the Docker container on Docker.io?  If so, what is it called? I'd be interested in looking at it.

I still use Vagrant quite a bit, but Docker has eaten much of Vagrant's lunch.

**Comment by julienchastang** [comment]
Ward,

I've been maintaining:

https://github.com/Unidata/Unidata-Dockerfiles/tree/master/python
https://registry.hub.docker.com/u/unidata/python/

Feel free to make any changes/updates.

**Comment by julienchastang** [comment]
no
