### ISSUE TITLE
matplotlib notebook broken

### ISSUE THREAD

**Issue by julienchastang** [Unidata/unidata-python-workshop#41]
currently complains about a DAP server error

**Comment by dopplershift** [comment]
Got too it last night, haven't committed as I'm looking for better colormaps. Again, you're too quick. :)

I think we're still at a point where it's best to focus on your own notebooks rather than worrying about making sure they all work perfectly.

**Comment by dopplershift** [comment]
And for the record, the DAP error comes from the NCDC thredds server throwing 503's right now, nothing wrong on our code. Luckily, I was able to point as ESRL's.

**Comment by dopplershift** [comment]
Closing in lieu of #19 , which is still open.
