### ISSUE TITLE
SIPHON_NCSS_Example_Cartopy notebook broken

### ISSUE THREAD

**Issue by julienchastang** [Unidata/unidata-python-workshop#43]
Currently complains about missing time1 variable

**Comment by dopplershift** [comment]
Hmmm...I changed this one to `time1` because it *was* complaining about the `time` variable missing. I wonder if we're just seeing some instability of the 0.25 GFS grib collections.

**Comment by lesserwhirls** [comment]
We need to look at the metadata to see which time variable is associated
with the variable we are interested in using.

Sean

**Comment by dopplershift** [comment]
Agreed now. I was hoping we could keep it simple, but, sadly as all things GRIB, that's not the case.

**Comment by lesserwhirls** [comment]
If only we had a nice getTimeAxis method like the CDM.

**Comment by dopplershift** [comment]
Open a bug on Siphon (seriously).

**Comment by dopplershift** [comment]
Working for me now. I think we punt on implementing any more complex solution to the time issue. I've added the getTimeAxis to the *MetPy* issue on a data object.
