### ISSUE TITLE
CompositeRadar notebook broken

### ISSUE THREAD

**Issue by julienchastang** [Unidata/unidata-python-workshop#44]
Complains about a color table issue near end of NB

**Comment by dopplershift** [comment]
Aware of this, gimme a chance to cut a new MetPy release.

You're working to quickly. :)

**Comment by julienchastang** [comment]
Sorry about that Ryan. I went through all the notebooks on the workshop machine, just in case. (We did find, and got to the bottom of at least one problem -- cartopy.)

**Comment by dopplershift** [comment]
No worries, it's just that I did the same thing yesterday on the machines after I fixed cartopy (and proj4 after that).

I feel like we're trying so hard to work fast that we're working horribly inefficiently and duplicating effort--which is really what we can ill afford right now.

**Comment by dopplershift** [comment]
MetPy 0.2.1 has been cut and uploaded to binstar. I've verified on my mac that getting up to date packages fixes the problem.
