### ISSUE TITLE
Send out email to workshop attendees by Friday (7/17)

### ISSUE THREAD

**Issue by julienchastang** [Unidata/unidata-python-workshop#47]
Send out email to workshop attendees by Friday (7/17).

**Comment by dopplershift** [comment]
What's the content of said email?

**Comment by julienchastang** [comment]
We've done something like this every previous year. (Links not working, I'll fix those later.)  Feel free to edit, modify:

----
Hello Workshop Attendees, 

Thank you for signing up for "Using Unidata Technologies with Python". We are excited to be presenting this workshop.

Desktop computers will be provided for workshop attendees. However, if you plan on working on your own laptop, please read these "installation instructions". Time will also be set aside during the workshop for software installation.

If you wish to bring your data to the workshop, we may have the opportunity of exploring your data with Python at some point over the course of the three days.

In the days before attending the workshop, it could be helpful to briefly review some Python fundamentals. We will do our best to get you up-to-speed as quickly as we can, but having some familiarity with Python will be useful. To that end, here is some material you may wish to skim before the workshop. 

1) Online lectures on scientific computing with Python, using IPython notebooks. https://github.com/jrjohansson/scientific-python-lectures#online-read-only-versions 

2) Online Python Scientific Lecture Notes - http://scipy-lectures.github.io/ 

3) Home page for the book "A Hands-On Introduction to Using Python in the Atmospheric and Oceanic Sciences" http://www.johnny-lin.com/pyintro/ 

4) O'Reilly Book "Python for Data Analysis" http://shop.oreilly.com/product/0636920023784.do. The appendix of "Python for Data Analysis" has a nice Python introduction section. 

Best Wishes, 

Unidata Python Group 

http://www.unidata.ucar.edu/events/2015TrainingWorkshop/

**Comment by dopplershift** [comment]
Forgot about that, glad you didn't. Looks good to me. We can discuss more tomorrow, but after that I say we just send it and give the attendees more lead time.
