### ISSUE TITLE
Thoughts for next time.

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#51]
Go ahead and capture any take aways from this time.

**Comment by dopplershift** [comment]
I don't think the radar composites notebook really serve much purpose right now, as it's just a simple opendap example. Things that should fold elsewhere:
- [ ] Pulling projection information out of netcdf variable ('LambertConformal')
- [ ] Using cartopy to do lcc -> orthographic

**Comment by rsignell-usgs** [comment]
You might like this Notebook, which uses Siphon, Xray, and Cartopy to view HRRR, stealing from @julienchastang and @dopplershift examples...
http://nbviewer.ipython.org/gist/rsignell-usgs/310b790a3a2cfdc8d06e

**Comment by dopplershift** [comment]
Can you update your x-ray PR here with this one? I really like the final result in this new notebook.

**Comment by rsignell-usgs** [comment]
you just like it because I used Siphon.... :smiley_cat:

**Comment by dopplershift** [comment]
It's not the *only* reason--the image in this one is nice and high res.

On Thu, Jul 23, 2015 at 12:30 PM, Rich Signell <notifications@github.com>
wrote:

> you just like it because I used Siphon.... [image: :smiley_cat:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unidata/unidata-python-workshop/issues/51#issuecomment-124200151>
> .
>



-- 
Ryan May
Software Engineer
UCAR/Unidata
Boulder, CO

**Comment by WardF** [comment]
From a conversation I had with Josh (regular Josh, not summer Josh), I'm wondering if there is room for a general "Here's how to use Jupyter Notebook/Python to do a generic **robust** statistical analysis" talk next year.  This would serve the following purposes:

1. Show off "general" python for data analysis, before jumping into our focus area.  
2. Convince the audience (or simply reinforce the notion) that *robust* statistics are a good thing to know, and that there is value in calculating more than a mean and/or standard deviation. For example:
    * Determining the distribution of observations.
    * Comparing non-normal/non-bimodal distributions.
    * Determining if the data contains any information or is it numerically indistinguishable from noise.
    * etc.

These aren't advanced topics, and I know *our* community has a handle on it in general, but they are things that are sometimes lacking in *other* scientific disciplines.   Anyways, it's a talk I'd be happy to give, if we decide it's worthwhile and fits within the larger workshop.

**Comment by jclark754** [comment]
@WardF, I take offense to being called 'summer' Josh. I thought we had settled on the more complementary 'young' Josh....

**Comment by jrleeman** [comment]
Anything still relevant here @dopplershift?
