### ISSUE TITLE
Siphon_XRAY_Cartopy_HRRR currently giving errors

### ISSUE THREAD

**Issue by julienchastang** [Unidata/unidata-python-workshop#57]
Siphon_XRAY_Cartopy_HRRR currently giving errors. see
http://mybinder.org/repo/Unidata/unidata-python-workshop

**Comment by dopplershift** [comment]
Likely due to the machine that was hosting our HRRR data (thredds-jumbo, aka. lead) being down.

**Comment by lesserwhirls** [comment]
This is because it is referencing thredds-jumbo, which is currently not in service. Hopefully soon, but until then, we should move away from using the GSD HRRR to the NCEP HRRR:

http://thredds.ucar.edu/thredds/catalog/grib/NCEP/HRRR/CONUS_2p5km/catalog.html

In fact, a simple change of the catalog url to:

http://thredds.ucar.edu/thredds/catalog/grib/NCEP/HRRR/CONUS_2p5km/latest.xml

and changing the temperature variable to:

Temperature_height_above_ground

should work. I will have a PR here soon.

**Comment by julienchastang** [comment]
Thanks. I am now getting

`query.lonlat_box(45, 41., -67, -77)`

`HTTPError: Error accessing http://thredds.ucar.edu/thredds/ncss/grib/NCEP/HRRR/CONUS_2p5km/HRRR_CONUS_2p5km_20160204_1300.grib2?var=Temperature_height_above_ground&temporal=all&south=-67&east=41.0&north=-77&west=45&accept=netcdf4: Invalid bbox. Bounding Box must have north > south
`

Though, according to the [docs](http://siphon.readthedocs.org/en/stable/api/http_util.html?highlight=lonlat_box#siphon.http_util.DataQuery.lonlat_box) your call is correct, I believe.

**Comment by lesserwhirls** [comment]
I think it depends on which version of Siphon you are using - the order of
the variable input of the bounding box changed. I was able to run it just
fine on the mybinder site, which I think uses an older version. We'll need
to update this once we cut a new release of siphon.

**Comment by julienchastang** [comment]
`0.3.2` is the latest stable, I believe. That's what I am working with.

**Comment by dopplershift** [comment]
Make sure you use the 'latest' docs: https://siphon.readthedocs.org/en/latest/

On those it should be: `lonlat_box(west, east, south, north)`

Or just use the docstring for the version you're using :smiling_imp: 

Apparently stable docs didn't build for 0.3.2. *sigh*

**Comment by lesserwhirls** [comment]
All we needed to do is to make the bounding box call used keyword
arguments, which will work with any version. I also fixed up getting the
time string...xarray's method of using var.DIM_NAME will not always work,
and the dimension name can and will change.
