### ISSUE TITLE
Notes from Madison workshop

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#79]
Here's a dump of the notes we took while giving the workshop in Madison; these need to be turned into individual issues at some point:

Workshop notes

TextWrangler for mac if users do not want to use command line - add as a suggestion for mac users? Notepad for windows, gedit for linux?
Types in Python - dangerous or not?
git add - didn’t we already add?
Do not have them make their own plot in the jupyter-examples/ 3. Plotting.ipynb , as this is covered in intro to numpy and matplotlib notebook
intro to numpy and matplotlib notebook - reword the “reduce by faster of three” exercise prompt. Maybe “For each dimension, select every third element”\
busted link in “sharing notebooks” jupyter example
Link to Docs
Presenter notes - scope of exercise, how interactive, how detailed

Things to add to site:

Resource on types in Python
Add bash config stuff for git prompt modifications
Find GIT cheat sheet
PEPs dealing with types in base python?
git ssl issues:  git -c http.sslVerify=false clone …
Anaconda (old version clashes???)

Day 2:

Might be good to do pythonic data analysis at before read/write netCDF?

Pythonic data analysis
User getting error reading netCDF. LD_LIBRARY_PATH is set to look in several places for libs, and the end result is that it is finding an older copy of HDF5, which is causing it to be loaded instead of the condo version. This causes the notebook kernel to restart when trying to open a netCDf files, due to a library incompatibility.
make variable names and linestyles separate lists (around cell 10 in solutions notebook)? Makes it more readable.
states dict - capital not capitol
show adding scalar to array with units.
MetPy Units and Upper Air
Remove StringIO from import in cell 2
add hodograph
Siphon HRRR Carroty
list variables from ncss object: ncss.variables
MetPy Surface
Delete time delta from “now”
Radar
Sort stations
Remove carroty bug code

Round 2:

Day 1: 

pint<0.7 in environment.yml -> version needs to go
Why _isn’t_ the interactive widgets (or _all_ from jupyter) example more domain specific?
Seriously, we need to murder pylab from the jupyter examples
We should also try to standardize a few more things in the notebooks (subplots vs. add_subplots vs. axes())

Siphon Carroty HRRR

remove calls to plot and use ax, fig objects instead

add colorer and label

ax.set_title("time[t_step].isoformat()")

cax = fig.colorbar(mesh)

cax.set_label(ncvar.units)

Pythonic data analysis lists language features, then jumps into an advanced Matplotlib example with no warning—need to tie that first section into introduction

Ryan _really_ needs to re-examine exercise questions

The workshop page should have a top-level set of resources, cheatsheets, and links to relevant documentation for numpy, matplotlib, metpy, etc.

**Comment by dopplershift** [comment]
Survey results: https://www.surveymonkey.com/results/SM-CSJLN8ST/

What could we improve about the workshop?
```
I think more examples directly using phython in the terminal might have been helpful. In general, more hands-on and less lecture.
7/1/2016 8:14 AM View respondent's answers

N/A
6/29/2016 3:22 PM View respondent's answers
I can't think of anything
6/28/2016 11:01 AM View respondent's answers

Introducing an object-oriented approach to Python programming
6/28/2016 10:52 AM View respondent's answers

In the Jypyter notebooks, the majority of the code was already fully entered and all we had to do was Shift+Enter to evaluate it. While the instructors did a good job explaining everything, maybe having a little more typing for the trainees would be good, like maybe a few blank spaces here and there for us to fill in.
6/27/2016 1:18 PM View respondent's answers

Can't think of anything right now. Will email if I do.
6/27/2016 12:55 PM View respondent's answers

Maybe 2 10 min breaks after lunch instead of 1 15 min break.
6/27/2016 8:29 AM View respondent's answers

If starting with numpy python, it might be helpful to send some introductory resources for those who do not have experience with python. Coursera, Lynda Tutorials or even other good resources. Some here like "Learn Python the Hard Way..." which has been exactly that for me. I prefer UofM's python coursera course. It would just be a suggestion which might be helpful and participants could choose to prepare ahead or not.
6/24/2016 10:32 AM View respondent's answers

nothing
6/24/2016 8:45 AM View respondent's answers

Workshop was very specific to the products Unidata provided. I would describe it as "here's how to use Python so you can use our products" and not "here's how to use Python, but since you need something to plot, we'll use our data"
6/24/2016 7:37 AM View respondent's answers

The workshop was dominated by using jupyter notebooks. It would have been good to have one example of writing and executing regular python code in .py files. We never actually ran the test.py code that we wrote.
6/23/2016 11:00 PM View respondent's answers

Jupyter tool is good. Hands-on examples sometime were a bit challenging given the previous information in the notebook. Start with an easy example and then more difficult ones.
6/23/2016 3:55 PM View respondent's answers

Make a cheat sheet for each module.
6/23/2016 3:03 PM View respondent's answers
```

and Any other suggestions?
```
More emphasis on the basics of Python would have also been helpful
7/1/2016 8:14 AM View respondent's answers

Just wanted to say "great stuff" (this is Leigh Orf, Pete & I had beer at the Union with you). I will be making my way through much of the material on my "spare time". Conda is an exceptionally cool discovery for me. Keep up the good work.
6/29/2016 3:22 PM View respondent's answers

Nope.
6/28/2016 11:01 AM View respondent's answers

A user asked about the enumerate function, so it was covered. However, it might be good to add a quick example of enumerate to the actual training. I'm new to Python, but I've heard a lot about enumerate... maybe it's not as important as I think it is though.
6/27/2016 1:18 PM View respondent's answers

Perhaps find a way to have the class collaborate on notebook answers during class that then go through the github steps of creating issues forking, etc. If students are exposed to git add/commit push, issue tracking consistently throughout class, they may become much more comfortable with it.
6/24/2016 10:32 AM View respondent's answers

We need more
6/24/2016 8:45 AM View respondent's answers

None -- Thank you, Ryan and Sean!
6/23/2016 8:38 PM View respondent's answers

Sean and Ryan really know their stuff. Good work!
6/23/2016 3:55 PM View respondent's answers

Just better online documentation and more examples exploring all the functions.
6/23/2016 3:03 PM View respondent's answers
```

**Comment by jrleeman** [comment]
@dopplershift - Anything in here you want to keep? Much of it is outdated now.

**Comment by dopplershift** [comment]
Nah.
