### ISSUE TITLE
Jupyter Intro Material

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#83]
- Need to update to the latest versions from Jupyter
- No need to experiment with plotting in `jupyter-examples/ 3. Plotting.ipynb`
- Eradicate all mention of `pylab`

**Comment by dopplershift** [comment]
Also fix busted link in "sharing notebooks" example

**Comment by dopplershift** [comment]
Make the example code more domain relevant.

**Comment by dopplershift** [comment]
Here are the new examples, which have changed significantly:

http://nbviewer.jupyter.org/github/jupyter/notebook/tree/master/docs/source/examples/Notebook/

@WardF how would you feel teaching from these? Should I pull these into our repo?

**Comment by dopplershift** [comment]
We have new content this time around. See how that goes and make new notes as necessary.

**Comment by WardF** [comment]
I missed this. Sorry.  Working on material now will pull from these as best I can.

**Comment by dopplershift** [comment]
No worries.
