### ISSUE TITLE
Why Vagrant instead of native Anaconda install?

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/unidata-python-workshop#9]
For the workshop, why have folks use a virtual machine via Vagrant instead of native Anaconda install? Is it because you are using conda modules that are not built yet for Mac and/or Windows?
If so, which ones haven't been built yet?

**Comment by WardF** [comment]
Pinging this issue to see if there are any objections to closing it out.  I think it's resolved?

**Comment by dopplershift** [comment]
No objections here.
