### ISSUE TITLE
Update for MetPy surface notebook

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#91]
- Delete time delta from "now"

**Comment by dopplershift** [comment]
Not sure we're pulling out the station metadata properly since we're not using the `stationIndex` variable. I've learned that we need this elsewhere; it'd be good to actually teach our attendees how to use our tools properly.

**Comment by jrleeman** [comment]
Fixed in #123  or #157 @dopplershift?

**Comment by dopplershift** [comment]
Fixed in #188 .
