### ISSUE TITLE
Some easy option for Animations?

### ISSUE THREAD

**Issue by brianmapes** [Unidata/unidata-python-workshop#92]
Looking through the notebooks, it is hard to find an example if inserting an animated .gif or other animation format. Have you got a good easy one? Googling around is frustrating. It seems harder than it should need to be. Help, middle-sized ally Unidata! I can't see over the grass roots!

**Comment by dopplershift** [comment]
Well there's already one in: https://github.com/Unidata/unidata-python-workshop/blob/master/notebooks/GINI%20Satellite%20with%20MetPy%20and%20Siphon.ipynb

Also there's the notebook I put together for the Amazon AWS NEXRAD data: https://nbviewer.jupyter.org/gist/dopplershift/356f2e14832e9b676207

Both of these use h264 encoded video and should be compatible with most browsers. The problem with teaching this to the average user is that getting ffmpeg installed on windows can be a real chore. This should get easier when matplotlib/matplotlib#4821 is merged, which will merge JSAnimation, which gives an html5-based javascript representation of Animations for the notebook.

**Comment by brianmapes** [comment]
Thanks!

Brian Mapes
This message was typed on a cell phone, please forgive its terseness and any errors.

On Aug 26, 2016, at 9:11 PM, Ryan May <notifications@github.com<mailto:notifications@github.com>> wrote:


Well there's already one in: https://github.com/Unidata/unidata-python-workshop/blob/master/notebooks/GINI%20Satellite%20with%20MetPy%20and%20Siphon.ipynb<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Unidata_unidata-2Dpython-2Dworkshop_blob_master_notebooks_GINI-2520Satellite-2520with-2520MetPy-2520and-2520Siphon.ipynb&d=DQMFaQ&c=y2w-uYmhgFWijp_IQN0DhA&r=6e7NDZhC34cc1mCaueSQWw&m=CpMd4e2rycik-8Y95novK8Qi8SV-Nz3LIpnh8U_i8ZU&s=amZR9Kd9PpzmxXgKuKRN6B-fWiP87eBGkEIG32hKWPM&e=>

Also there's the notebook I put together for the Amazon AWS NEXRAD data: https://nbviewer.jupyter.org/gist/dopplershift/356f2e14832e9b676207<https://urldefense.proofpoint.com/v2/url?u=https-3A__nbviewer.jupyter.org_gist_dopplershift_356f2e14832e9b676207&d=DQMFaQ&c=y2w-uYmhgFWijp_IQN0DhA&r=6e7NDZhC34cc1mCaueSQWw&m=CpMd4e2rycik-8Y95novK8Qi8SV-Nz3LIpnh8U_i8ZU&s=wsdb9-pUEnofgjWjJ_1CKPlcfLfRmbQ5m4nvsaEVX-M&e=>

Both of these use h264 encoded video and should be compatible with most browsers. The problem with teaching this to the average user is that getting ffmpeg installed on windows can be a real chore. This should get easier when matplotlib/matplotlib#4821<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_matplotlib_matplotlib_pull_4821&d=DQMFaQ&c=y2w-uYmhgFWijp_IQN0DhA&r=6e7NDZhC34cc1mCaueSQWw&m=CpMd4e2rycik-8Y95novK8Qi8SV-Nz3LIpnh8U_i8ZU&s=4R0_unA_XWqNdXcYG70x6IY6BkZeBvTiFg1QZC4trd0&e=> is merged, which will merge JSAnimation, which gives an html5-based javascript representation of Animations for the notebook.

**Comment by brianmapes** [comment]
Is animated gif possible? A standard output from IDV/isl scripts. Why is .gif so hard?? We googled for like half an hour.

Brian Mapes
This message was typed on a cell phone, please forgive its terseness and any errors.

On Aug 26, 2016, at 9:11 PM, Ryan May <notifications@github.com<mailto:notifications@github.com>> wrote:


Well there's already one in: https://github.com/Unidata/unidata-python-workshop/blob/master/notebooks/GINI%20Satellite%20with%20MetPy%20and%20Siphon.ipynb<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Unidata_unidata-2Dpython-2Dworkshop_blob_master_notebooks_GINI-2520Satellite-2520with-2520MetPy-2520and-2520Siphon.ipynb&d=DQMFaQ&c=y2w-uYmhgFWijp_IQN0DhA&r=6e7NDZhC34cc1mCaueSQWw&m=CpMd4e2rycik-8Y95novK8Qi8SV-Nz3LIpnh8U_i8ZU&s=amZR9Kd9PpzmxXgKuKRN6B-fWiP87eBGkEIG32hKWPM&e=>

Also there's the notebook I put together for the Amazon AWS NEXRAD data: https://nbviewer.jupyter.org/gist/dopplershift/356f2e14832e9b676207<https://urldefense.proofpoint.com/v2/url?u=https-3A__nbviewer.jupyter.org_gist_dopplershift_356f2e14832e9b676207&d=DQMFaQ&c=y2w-uYmhgFWijp_IQN0DhA&r=6e7NDZhC34cc1mCaueSQWw&m=CpMd4e2rycik-8Y95novK8Qi8SV-Nz3LIpnh8U_i8ZU&s=wsdb9-pUEnofgjWjJ_1CKPlcfLfRmbQ5m4nvsaEVX-M&e=>

Both of these use h264 encoded video and should be compatible with most browsers. The problem with teaching this to the average user is that getting ffmpeg installed on windows can be a real chore. This should get easier when matplotlib/matplotlib#4821<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_matplotlib_matplotlib_pull_4821&d=DQMFaQ&c=y2w-uYmhgFWijp_IQN0DhA&r=6e7NDZhC34cc1mCaueSQWw&m=CpMd4e2rycik-8Y95novK8Qi8SV-Nz3LIpnh8U_i8ZU&s=4R0_unA_XWqNdXcYG70x6IY6BkZeBvTiFg1QZC4trd0&e=> is merged, which will merge JSAnimation, which gives an html5-based javascript representation of Animations for the notebook.

**Comment by dopplershift** [comment]
I'm surprised you're having such problems finding any resources. This is the first hit when i search for "matplotlib animation gif": https://jakevdp.github.io/blog/2013/05/28/a-simple-animation-the-magic-triangle/

Based on that, the easiest way to make an animated gif is to use the 'imagemagick' writer when saving an animation:

```python
anim.save('MagicTriangle.gif', writer='imagemagick')
```

I usually don't use animated gifs, since the tools for viewing them have no playback controls--and I'm experienced enough getting ffmpeg (for mpeg4) on linux/osx.

**Comment by brianmapes** [comment]
We're looking for a route to have IDV's animation ouputs, ideally creatable from an .isl script, go into .ipynb notebooks (this pathway will work on all platforms). I thought .gif might be the least problematic (.mov and .avi have not seemed very universal to me, but either could be OK if so). Here is the animation formats list from IDV: 

![image](https://cloud.githubusercontent.com/assets/2086210/18025221/efb522e6-6bdf-11e6-8352-22ed90f54279.png)

import IPython.display as IPdisplay
IPdisplay.Image('/Users/bem/Downloads/weirdstuff.gif')

ValueError: Cannot embed the 'gif' image format

**Comment by dopplershift** [comment]
Well, embedding in a notebook (so the browser can render) might be the most straightforward of those, but gif support in the notebook isn't direct: jupyter/notebook#713

You can work around it by using python to read the data from the file and embedding that: 
```python
with open('yourfile.gif','rb') as f:
    display(Image(f.read()), format='png')
```

**Comment by brianmapes** [comment]
Hey, now that works! With the implied imports of course

from IPython.display import Image
from IPython.display import display
with open('/Users/bem/Downloads/weirdstuff.gif','rb') as f:
    display(Image(f.read()), format='png')

Now I suppose one wishes for controls... and then it is back to a slippery slope to 20-line gibberish... but this will do, this will do!
